Subtile requirement: $(check_for_update) spawns a new shell. If the function fails, pass exit code and it's message to caller

diff --git a/bin/check_yum b/bin/check_yum
--- a/bin/check_yum
+++ b/bin/check_yum
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-readonly __VERSION="1.0.0"
+readonly __VERSION="1.0.1"
 readonly __NAME="check_yum"
 
 readonly DNF="/usr/bin/dnf"
@@ -248,6 +248,12 @@ function main() {
     fi
 
     update_count="$(check_for_updates)"
+    # Subtile requirement: $(check_for_update) spawns a new shell. If the function fails, pass exit code and it's message to caller
+    rc=$?
+    if [ ${rc} -ne 0 ]; then
+        echo "${update_count}"
+        exit ${rc}
+    fi
 
     security_count="$(echo "${update_count}" | cut -d ',' -f 1)"
     non_security_count="$(echo "${update_count}" | cut -d ',' -f 2)"
